apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app.kubernetes.io/part-of: event-driven-order-platform

resources:
  - order-service.yaml
  - payment-service.yaml
  - inventory-service.yaml
  - notification-service.yaml
