apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: eda-dev

resources:
  - ../../base
  - namespace.yaml
  - ingress.yaml

patchesStrategicMerge:
  - patch-images.yaml
  - patch-config-dev.yaml
  - patch-secrets-dev.yaml
