apiVersion: v1
kind: Secret
metadata:
  name: order-service-secret
stringData:
  ORDER_DB_USERNAME: order_user
  ORDER_DB_PASSWORD: order_pass
---
apiVersion: v1
kind: Secret
metadata:
  name: payment-service-secret
stringData:
  PAYMENT_DB_USERNAME: payment_user
  PAYMENT_DB_PASSWORD: payment_pass
---
apiVersion: v1
kind: Secret
metadata:
  name: inventory-service-secret
stringData:
  INVENTORY_DB_USERNAME: inventory_user
  INVENTORY_DB_PASSWORD: inventory_pass
---
apiVersion: v1
kind: Secret
metadata:
  name: notification-service-secret
stringData:
  NOTIFICATION_DB_USERNAME: notification_user
  NOTIFICATION_DB_PASSWORD: notification_pass
